Models/OrderSummary.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ProntoChef.Models
{
    public class OrderSummary
    {
        [Key]
        public int OrderSummaryId { get; set; }

        public int UserId { get; set; }

        public string OrderDate { get; set; }

        public string OrderAddress { get; set; }

        public string Note { get; set; }

        public decimal TotalPrice { get; set; }

        public string State { get; set; }

        public ICollection<OrderItem> OrderItems { get; set; }

        public User User { get; set; }
    }
}

Controllers/OrderSummariesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProntoChef.Models;

namespace ProntoChef.Controllers
{
    public class OrderSummariesController : Controller
    {
        private DBContext db = new DBContext();

        [Authorize]
        public ActionResult Summary()
        {
            int userId = Convert.ToInt32(HttpContext.User.Identity.Name);
            OrderSummary summId = db.OrderSummaries.Where(o => o.UserId == userId && o.State == "NON EVASO").FirstOrDefault();

            if (summId != null)
            {
                OrderSummary summary = db.OrderSummaries
                                    .Include(o => o.OrderItems)
                                    .Include(o => o.OrderItems.Select(i => i.Product))
                                    .SingleOrDefault(o => o.OrderSummaryId == summId.OrderSummaryId);
                if (summary != null)
                {
                    ViewBag.SumPrice = summary.OrderItems.Sum(i => i.ItemPrice);
                    return View(summary);
                }
            }
            return View();
        }


        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var orderSummaries = db.OrderSummaries.Include(o => o.User);
            return View(orderSummaries.ToList());
        }

        [Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderSummary orderSummary = db.OrderSummaries.Find(id);
            if (orderSummary == null)
            {
                return HttpNotFound();
            }
            return View(orderSummary);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.Users, "UserId", "Email");
            return View();
        }

       
        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderSummaryId,UserId,OrderDate,OrderAddress,Note,TotalPrice,State")] OrderSummary orderSummary)
        {
            if (ModelState.IsValid)
            {
                db.OrderSummaries.Add(orderSummary);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.Users, "UserId", "Email", orderSummary.UserId);
            return View(orderSummary);
        }

        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            OrderSummary orderSummary = db.OrderSummaries.Find(id);

            if (orderSummary == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Users, "UserId", "Email", orderSummary.UserId);
            return View(orderSummary);
        }

        
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderAddress,Note,OrderDate")] OrderSummary orderSummary, int id)
        {
            if (id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            OrderSummary orderToSend = db.OrderSummaries.Find(id);

            if (orderToSend == null)
            {
                return HttpNotFound();
            }

            decimal sumPrice = db.OrderItems.Where(o => o.OrderSummaryId == id).Sum(i => i.ItemPrice);

            if (ModelState.IsValid)
            {
                orderToSend.OrderDate = orderSummary.OrderDate;
                orderToSend.TotalPrice = sumPrice;
                orderToSend.State = "EVASO";
                orderToSend.OrderAddress = orderSummary.OrderAddress;
                orderToSend.Note = orderSummary.Note;

                db.Entry(orderToSend).State = EntityState.Modified;
                db.SaveChanges();

                TempData["OrderSuccess"] = true;

                return RedirectToAction("Index", "Home");
            }

            return View(orderToSend);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderSummary orderSummary = db.OrderSummaries.Find(id);
            if (orderSummary == null)
            {
                return HttpNotFound();
            }
            return View(orderSummary);
        }

        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OrderSummary orderSummary = db.OrderSummaries.Find(id);
            db.OrderSummaries.Remove(orderSummary);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteItem(int id)
        {
            OrderItem item = db.OrderItems.Find(id);
            if (item != null)
            {
                db.OrderItems.Remove(item);
                db.SaveChanges();
                TempData["ItemRemoved"] = true;
                return RedirectToAction("Summary");
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize(Roles = "Admin")] 
        public ActionResult OrdiniEvasi()
        {
            var ordiniEvasi = db.OrderSummaries.Where(o => o.State == "EVASO").Count();
            return Json(ordiniEvasi, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult IncassiPerGiorno(int id)
        {
            var ordiniTotali = db.OrderSummaries.Where(o => o.State == "EVASO").ToList();
            decimal incassoPerGiorno = 0;

            foreach (var order in ordiniTotali)
            {
                DateTime orderDateTime = DateTime.Parse(order.OrderDate);

                if (orderDateTime.Day == id)
                {
                    incassoPerGiorno += order.TotalPrice;
                }
            }

            return Json(incassoPerGiorno, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/OrderSummaries/Create.cshtml
@model ProntoChef.Models.OrderSummary

@{
    ViewBag.Title = "Create";
}
<head>
    <style>
        body {
            color: white;
        }

        h2, th, td {
            color: white;
        }
    </style>
</head>
<h2>Crea Prenotazione</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "Email :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderDate,"Data :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderAddress,"Indirizzo :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note,"Note :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalPrice,"Totale :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State,"Stato : ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aggiungi" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Torna Indietro", "Index", null, new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/OrderSummaries/Delete.cshtml
@model ProntoChef.Models.OrderSummary

@{
    ViewBag.Title = "Delete";
}
<head>
    <style>
        body {
            color: white;
        }

        h2, th, td {
            color: white;
        }
    </style>
</head>
<h2>Stai cancellando una prenotazione, sei davvero sicuro?</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("ID :")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayName("Data :")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayName("Indirizzo :")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderAddress)
        </dd>

        <dt>
            @Html.DisplayName("Note :")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayName("Totale :")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

        <dt>
            @Html.DisplayName("Stato :")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Elimina" class="btn btn-danger" /> 
            @Html.ActionLink("Torna Indietro", "Index", null, new { @class = "btn btn-info" })
        </div>
    }
</div>

Views/OrderSummaries/Details.cshtml
@model ProntoChef.Models.OrderSummary

@{
    ViewBag.Title = "Details";
}
<head>
    <style>
        body {
            color: white;
        }

        h2, th, td {
            color: white;
        }
    </style>
</head>
<h2>Dettagli pranotazione :</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("ID :")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayName("Data :")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayName("Indirizzo :")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderAddress)
        </dd>

        <dt>
            @Html.DisplayName("Note :")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayName("Totale :")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

        <dt>
            @Html.DisplayName("Stato :")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifica", "Edit", new { id = Model.OrderSummaryId },new {@class = "btn btn-success"})
    @Html.ActionLink("Torna Indietro", "Index", null, new { @class = "btn btn-info" })
</p>

Views/OrderSummaries/Edit.cshtml
@model ProntoChef.Models.OrderSummary

@{
    ViewBag.Title = "Edit";
}
<head>
    <style>
        body {
            color: white;
        }

        h2, th, td {
            color: white;
        }
    </style>
</head>
<h2>Modifica Prenotazione</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
 
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderSummaryId)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderDate,"Data :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderAddress,"Indirizzo :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note,"Note :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalPrice,"Totale :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State,"Stato :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Modifica" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Torna Indietro", "Index", null, new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/OrderSummaries/Index.cshtml
@model IEnumerable<ProntoChef.Models.OrderSummary>

@{
    ViewBag.Title = "Index";
}
<head>
    <style>
        body {
            color: white;
        }

        h2, th, td {
            color: white;
        }
        .custom-link-style {
            color: rgb(234, 18, 126);
            text-decoration: none;
            font-size: 16px;
            cursor: pointer;
            transition: font-size 0.3s ease;
            padding: 5px;
        }

            .custom-link-style:hover {
                font-size: 18px;
                color: white;
                font-size: large;
            }
        tr {
            border-color: #681747;
            border-style: solid;
            border-width: 0px;
        }
    </style>
</head>
<h2>Elenco Prenotazioni</h2>

<p>
    @Html.ActionLink("Crea Prenotazione", "Create", null, new { @class = "custom-link-style" })
</p>
<table class="table">
    <tr>
        <th>
    @Html.DisplayName("ID")
        </th>
        <th>
            @Html.DisplayName("Email")
        </th>
        <th>
            @Html.DisplayName("Data")
        </th>
        <th>
            @Html.DisplayName("Indirizzo")
        </th>
        <th>
            @Html.DisplayName("Note")
        </th>
        <th>
            @Html.DisplayName("Totale")
        </th>
        <th>
            @Html.DisplayName("Stato")
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Note)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.ActionLink("Modifica", "Edit", new { id = item.OrderSummaryId }, new { @class = "btn btn-success btn-sm" })
            @Html.ActionLink("Dettagli", "Details", new { id = item.OrderSummaryId }, new { @class = "btn btn-secondary btn-sm" })
            @Html.ActionLink("Elimina", "Delete", new { id = item.OrderSummaryId }, new { @class = "btn btn-danger btn-sm" })
        </td>
    </tr>
}

</table>

Views/OrderSummaries/Summary.cshtml
@model ProntoChef.Models.OrderSummary

@{
    ViewBag.Title = "Summary";
}

@section styles
{
    <style>
        .summary {
            width: 80%;
            box-sizing: border-box;
            margin: 25px auto 0 auto;
            padding: 18px;
            border: 3px solid #721847;
            border-radius: 10px;
        }

        
        body {
            color: white;
        }

        h2, h3, h4, th, td {
            color: white;
        }
        .card-text{
            color:white;
        }
        .btncust {
            background-color: #390F47;
        }
        .imgsummary{
            object-fit:cover;
        }

    </style>
   
}

@if (TempData["ItemRemoved"] != null)
{
    <div class="alert alert-success" role="alert">
        Chef rimosso!
    </div>
}

<div class="container">
    <div class="summary">
        <h2>...Ecco lo Chef che ti delizierà </h2>
        <hr />
        @if (Model == null || !Model.OrderItems.Any())
        {
            <h2 class="text-center my-5">Ops non ci sono Chef prenotati! </h2>
        }
        else
        {
            <div class="d-flex flex-wrap justify-content-between">
                @foreach (var item in Model.OrderItems)
                {
                    <div class="card m-3 bg-transparent border border-white" style="max-width: 450px;  overflow:hidden">
                        <div class="row g-0">
                            <div class="col-md-4 bg-transparent">
                                <img src="@item.Product.ProductImage" class="imgsummary rounded-start h-100 w-100" alt="...">
                            </div>
                            <div class="col-md-8 bg-transparent">
                                <div class="card-body p-1">
                                    <h5 class="card-title align-text-center text-white">@item.Product.ProductName x @item.Quantity Cooking Session</h5>
                                    <p class="card-text"> Etnia : @item.Product.Category</p>
                                    <div class="d-flex justify-content-between">
                                        <p class="card-text text-end">Prezzo Totale : @item.ItemPrice€</p>
                                        @using (Html.BeginForm("DeleteItem", "OrderSummaries", new { id = item.OrderItemId }, FormMethod.Post, new { @class = "d-inline mb-1" }))
                                        {
                                            @Html.AntiForgeryToken()
                                            <button type="submit" class="btn btn-danger">Elimina</button>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        }

        @if (Model != null && Model.State == "NON EVASO")
        {
            <div class="d-flex justify-content-around px-3">
                @using (Html.BeginForm("Edit", "OrderSummaries", new { id = Model.OrderSummaryId }, FormMethod.Post, new { @class = "w-50" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <h4>Data e Ora :</h4>
                        @Html.EditorFor(m => m.OrderDate, new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
                    </div>
                    <div class="form-group">
                        <h4 class="mt-1">Indirizzo :</h4>
                        @Html.EditorFor(m => m.OrderAddress, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    <div class="form-group">
                        <h4 class="mt-1">Informazioni Aggiuntive :</h4>
                        @Html.TextAreaFor(m => m.Note, new { @class = "form-control", rows = "3", placeholder = "Fai sapere allo Chef qualcosa in più!" })
                    </div>
                    <button class="btn text-white btncust mt-3">Conferma!</button>
                }
                <div class="text-end w-50">
                    <h3>Costo Totale : </h3>
                    <hr />
                    <h4>@ViewBag.SumPrice€</h4>
                </div>
            </div>
        }
    </div>
</div>